# Generated by Django 3.1.12 on 2026-04-01 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20260401_1035'),
    ]

    operations = [
    ]
